name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Prettier
        run: npm run prettier:ci
      - name: Test
        run: npm run test
      - name: Upload coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
