name: Publish Documentation

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm ci
      - name: Build
        run: npm run build:docs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          CLEAN: true
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
